version: '3'

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: myapp-mailhog
    ports:
      - 1025:1025
      - 8025:8025
    depends_on:
      - app
    networks:
      - appnet

  #MySQL Service
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: leocrmdb
    ports:
      - 7776:3306
    networks:
      - appnet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 7760:80
    networks:
      - appnet

#  l

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./backend/monolith/docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - db
    networks:
      - appnet

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./backend/monolith/docker/php/Dockerfile
    image: php:7.3-fpm
    container_name: server_php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./backend/monolith/docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - webserver
    networks:
      - appnet


  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - appnet

networks:
  appnet:
    driver: "bridge"
